version: '3'
services:
  tech-study-docker: 
    build: .
    image: xuzhengze/tech-study-docker
    volumes:
      - ./config:/root/tech-study-node/src/config
      - ./logs:/root/tech-study-node/src/logs
    container_name: tech-study-docker
    stdin_open: true 
    tty: true